name: Backend CI

on:
  push:
    paths:
      - 'backend/**'
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Lint check
      run: |
        echo "No linting yet — add ESLint later if needed"

    - name: Test (placeholder)
      run: |
        echo "No tests defined yet — add Jest or other test runner here"

    - name: Build Docker image
      run: docker build -t devops-api .

    # Optional: Push image to registry or deploy to Cloud Run in Phase 4
