name: Deploy Vue Frontend to Cloud Run

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'

    - name: Setup gcloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        export_default_credentials: true

    - name: Build and submit image
      run: |
        gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/vue-frontend .

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy vue-frontend \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/vue-frontend \
          --platform managed \
          --region ${{ secrets.GCP_REGION }} \
          --allow-unauthenticated
